### ISSUE TITLE
怎样使ispeak实现首页轮播，Butterfly主题

### ISSUE THREAD

**Issue by iwyang** [kkfive/kkapi-open#2]
以前的代码要怎样修改一下，才能实现首页轮播，请大佬教一下，谢谢。
```
top:
  - class_name: latestBB
    id_name:
    name: 最新说说
    icon: fas fa-bolt
    order: 2
    html: |
      <div class="swiper-container swiper-container-aside">
        <div class="swiper-wrapper swiper-weapper-aside"></div>
      </div>
      <a class="bb-btn button--animated" href="/say/" title="查看全部"><i class="far fa-hand-point-right fa-fw"></i> 查看更多 </a>
      <script>
        window.kkBBConfig = {
          limit: 10,
          blog:'/say/',
          api_url:
            'https://xxx/json/bber.json'//你的json url
        }
      </script>
      <script src="../img/js/butterfly-bber-swiper.min.js"></script>
```

**Comment by kkfive** [comment]
以下方法仅限**最新版**，即通过kkapi进行部署
以下方法仅限**最新版**，即通过kkapi进行部署
以下方法仅限**最新版**，即通过kkapi进行部署


我个人的方法是通过挂载在侧边栏，然后侧边栏引用js动态插入顶部轮播位置。
参考代码：

```yaml
bottom:
  - class_name: latestBB
    id_name:
    name: Ispeak
    icon: fas fa-bolt
    order: 2
    html: |
      <div class="swiper-container swiper-container-aside">
        <div class="swiper-wrapper swiper-weapper-aside"></div>
      </div>
      <a class="bb-btn button--animated" href="/speak/" title="查看全部"><i class="far fa-hand-point-right fa-fw"></i> 查看更多 </a>
      <script>
        window.kkBBConfig = {
          limit: 9,
          blog:'/speak',
          api_url: 'api地址',
          author: '你的用户token'
        }
      </script>
      <script src="https://cdn1.tianli0.top/npm/butterfly-speak-swiper@1.1.0/dist/index.min.js"></script>
```
